### ISSUE TITLE
HDD temperature reported incorrectly

### ISSUE THREAD

**Issue by yochananmarqos** [fredcox/gonha#8] opened 2020-08-01 00:29 UTC
My WDC HDD reports 107 C (actually 36 C) while my Samsung NVME M2 SSD reports 40 C (accurate).

**Comment by fredcox** [comment] 2020-08-01 00:54
> My WDC HDD reports 107 C (actually 36 C) while my Samsung NVME M2 SSD reports 40 C (accurate).

We are with one bug in this section "disks". But we are investigating. Please , wait one more time. Sorry

**Comment by fredcox** [comment] 2020-08-01 02:37
> My WDC HDD reports 107 C (actually 36 C) while my Samsung NVME M2 SSD reports 40 C (accurate).

Hi, i am go back. 

So, i thinking about hddtemp as daemon and it is one good option because the code is good . But i add the nvme section in wizard, and if the user want monitoring nvme temperature, in this case is necessary edit /etc/sudoers with sudo bypass to /usr/sbin/nvme. The version 1.5.9 is out now, please test and report any problem. thank you

**Comment by yochananmarqos** [comment] 2020-08-01 02:39
You do understand I'm seeing my NVME temp without running `nvme-cli` at all, right?

I'll check the new version in the morning.

**Comment by fredcox** [comment] 2020-08-01 02:42
> You do understand I'm seeing my NVME temp without running `nvme-cli` at all, right?
> 
> I'll check the new version in the morning.

How do I know the nvme device temp without nvme-cli? Please help me

**Comment by yochananmarqos** [comment] 2020-08-01 02:45
I already told you more than once. 

What kernel are you running? You need >=5.5.

**Comment by fredcox** [comment] 2020-08-01 02:54
> I already told you more than once.
> 
> What kernel are you running? You need >=5.5.

Ah, ok, i am running 5.4.0 because my distro (linux mint) is not publish 5.5 kernel

**Comment by yochananmarqos** [comment] 2020-08-01 02:59
Well, 5.4 is the current LTS kernel, but Ubuntu / Mint goes by their own most of the time. I'm using the latest stable kernel on Manjaro which is 5.7.

Can you add a kernel check and not require `nvme-cli` if it's >= 5.5?

**Comment by fredcox** [comment] 2020-08-01 03:19
> Well, 5.4 is the current LTS kernel, but Ubuntu / Mint goes by their own most of the time. I'm using the latest stable kernel on Manjaro which is 5.7.
> 
> Can you add a kernel check and not require `nvme-cli` if it's >= 5.5?

Yes, i will add kernel version >= 5.5 dependence and no more nvme-cli. I switch here to kernel 5.7.12 and sensors running nicely. So, i will integrate this in next version.

**Comment by fredcox** [comment] 2020-08-01 04:34
> > Well, 5.4 is the current LTS kernel, but Ubuntu / Mint goes by their own most of the time. I'm using the latest stable kernel on Manjaro which is 5.7.
> > Can you add a kernel check and not require `nvme-cli` if it's >= 5.5?
> 
> Yes, i will add kernel version >= 5.5 dependence and no more nvme-cli. I switch here to kernel 5.7.12 and sensors running nicely. So, i will integrate this in next version.

i was add kernel 5.5.x>= as dependency. And no more nvme-cli is necessary.

**Comment by yochananmarqos** [comment] 2020-08-01 14:44
With the latest commit, my WDC is showing 89 C when it's actually 89 F (32 C). My other temps show properly.

**Comment by fredcox** [comment] 2020-08-01 15:36
> With the latest commit, my WDC HDD is showing 89 C when it's actually 89 F (32 C). My other temps show properly.

32 Celsius is 89 F . I am working with this. Will remove this bug in the next release. Please, wait one more ti

**Comment by fredcox** [comment] 2020-08-01 17:34
> With the latest commit, my WDC HDD is showing 89 C when it's actually 89 F (32 C). My other temps show properly.

Hi, the release 1.6.4 is out now with a lot off bugs removing. Please test and send me feedback about your WDC HDD device. 
regards

**Comment by yochananmarqos** [comment] 2020-08-01 17:42
I chose Fahrenheit in the setup and all my temps are wrong. My CPU shows 170 F when it's actually about 160 F. My WDC HDD shows 230 F when it's about 96 F. My NVME M2 SSD shows 129 when it's about 103 F.

**Comment by fredcox** [comment] 2020-08-01 17:50
> I chose Fahrenheit in the setup and all my temps are wrong. My CPU shows 170 F when it's actually about 160 F. My WDC HDD shows 230 F when it's about 96 F. My NVME M2 SSD shows 129 when it's about 103 F.

If you choose Kelvin or Celsius in setup what temperature values?

**Comment by fredcox** [comment] 2020-08-01 17:56
> I chose Fahrenheit in the setup and all my temps are wrong. My CPU shows 170 F when it's actually about 160 F. My WDC HDD shows 230 F when it's about 96 F. My NVME M2 SSD shows 129 when it's about 103 F.

Please, run this python 3 script in your system and please send me the output here. 

```
import psutil

print(psutil.sensors_temperatures())

```

**Comment by yochananmarqos** [comment] 2020-08-01 18:05
> If you choose Kelvin or Celsius in setup what temperature values?

CPU an NVME temps are correct in Celsius, but my WDC HDD shows 93 C when it's actually 93 F.

> Please, run this python 3 script in your system and please send me the output here.

```
{'nvme': [shwtemp(label='Composite', current=37.85, high=84.85, critical=84.85), shwtemp(label='Sensor 1', current=37.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=37.85, high=65261.85, critical=65261.85)], 'k10temp': [shwtemp(label='Tctl', current=58.25, high=None, critical=None), shwtemp(label='Tdie', current=58.25, high=None, critical=None)], 'amdgpu': [shwtemp(label='edge', current=58.0, high=80.0, critical=80.0)]}
```

**Comment by fredcox** [comment] 2020-08-01 18:13
> y WDC HDD shows 93 C when it's actually 93 F.

what the output from command nc -v -v localhost 7634 in your system? I need this, please.

**Comment by yochananmarqos** [comment] 2020-08-01 19:21
```
localhost [127.0.0.1] 7634 open
|/dev/sda|WDC WD10SPZX-75Z10T2|93|F|Total received bytes: 36
Total sent bytes: 0
```

**Comment by fredcox** [comment] 2020-08-01 19:29
> ```
> localhost [127.0.0.1] 7634 open
> |/dev/sda|WDC WD10SPZX-75Z10T2|93|F|Total received bytes: 36
> Total sent bytes: 0
> ```

Oh, man. Your hddtemp inform the temperature in fahrenheit? Is it the cause off bad temperature in WDC  HDD. Please, you must to inform to hddtemp in /etc/default/hddtemp to force the temperature to celsius, because gonha get all temperatures in celsius , it is default on the all modules , its include psutil, so, inform the unit output hddtemp in Celsius only.

**Comment by yochananmarqos** [comment] 2020-08-01 19:34
Oh, I forgot about that. I did it that way for for my temperature readings in Conky.

However my CPU and NVME temps are still off in Fahrenheit.

**Comment by fredcox** [comment] 2020-08-01 19:39
> Oh, I forgot about that. I did it that way for for my temperature readings in Conky.
> 
> However my CPU and NVME temps are still off in Fahrenheit.

Install the new release 1.6.6 and show me the temps. please.

**Comment by yochananmarqos** [comment] 2020-08-01 20:09
```
localhost [127.0.0.1] 7634 open
|/dev/sda|WDC WD10SPZX-75Z10T2|36|C|Total received bytes: 36
Total sent bytes: 0
```

```
{'nvme': [shwtemp(label='Composite', current=40.85, high=84.85, critical=84.85), shwtemp(label='Sensor 1', current=40.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=38.85, high=65261.85, critical=65261.85)], 'k10temp': [shwtemp(label='Tctl', current=57.25, high=None, critical=None), shwtemp(label='Tdie', current=57.25, high=None, critical=None)], 'amdgpu': [shwtemp(label='edge', current=57.0, high=80.0, critical=80.0)]}
```

Fahrenheit:
![Screenshot from 2020-08-01 14-04-09](https://user-images.githubusercontent.com/5437803/89109674-83876b00-d400-11ea-84cb-3c7ea5181361.png)

Celsius:
![Screenshot from 2020-08-01 14-05-32](https://user-images.githubusercontent.com/5437803/89109678-8a15e280-d400-11ea-967b-81f3f1167b83.png)

**Comment by fredcox** [comment] 2020-08-01 20:38
> ```
> localhost [127.0.0.1] 7634 open
> |/dev/sda|WDC WD10SPZX-75Z10T2|36|C|Total received bytes: 36
> Total sent bytes: 0
> ```
> 
> ```
> {'nvme': [shwtemp(label='Composite', current=40.85, high=84.85, critical=84.85), shwtemp(label='Sensor 1', current=40.85, high=65261.85, critical=65261.85), shwtemp(label='Sensor 2', current=38.85, high=65261.85, critical=65261.85)], 'k10temp': [shwtemp(label='Tctl', current=57.25, high=None, critical=None), shwtemp(label='Tdie', current=57.25, high=None, critical=None)], 'amdgpu': [shwtemp(label='edge', current=57.0, high=80.0, critical=80.0)]}
> ```
> 
> Fahrenheit:
> ![Screenshot from 2020-08-01 14-04-09](https://user-images.githubusercontent.com/5437803/89109674-83876b00-d400-11ea-84cb-3c7ea5181361.png)
> 
> Celsius:
> ![Screenshot from 2020-08-01 14-05-32](https://user-images.githubusercontent.com/5437803/89109678-8a15e280-d400-11ea-967b-81f3f1167b83.png)

I discover what was wrong with Fahrenheit temperatures, was conversion python code. I Solve this now and release 1.6.8 is ok without this problem. Please test 1.6.8 and let me know if is ok.

**Comment by fredcox** [comment] 2020-08-01 20:43
I would like put your name and github on gonha README.md as colaborator on this project, because 
you helped a lot in development questions on this  project. 

May i put you as colaborator on this project?

**Comment by yochananmarqos** [comment] 2020-08-01 20:44
Sure. While you're at it, Could you link to the AUR packages in the `README`?

**Comment by fredcox** [comment] 2020-08-01 21:43
> I was using that to generate the `pkgver`.

Ok, man. I put you as colaborator, thank to colaboration. So, i was link the aur packages in README.md. 

I dont remove the version, but i was created one subroutine in python to search and recovery the version in file gonha/util.py, 
I did this to simplify and leave only one place to edit the version of the application.

**Comment by fredcox** [comment] 2020-08-01 21:44
> the weather is still in Celsius.

I switch the weather temp to user config option. I will make this now. In the next release it will be fixed.

**Comment by fredcox** [comment] 2020-08-01 22:07
> > I was using that to generate the `pkgver`.
> 
> Ok, man. I put you as colaborator, thank to colaboration. So, i was link the aur packages in README.md.
> 
> I dont remove the version, but i was created one subroutine in python to search and recovery the version in file gonha/util.py,
> I did this to simplify and leave only one place to edit the version of the application.

Ok, Mark, the weather temperature is ok with celsius, Fahrenheit and kelvin. I publish release 1.6.9 with fix.

**Comment by yochananmarqos** [comment] 2020-08-02 04:20
> the version in file gonha/util.py

Yeah, I saw that. I just hadn't figured out how to parse it yet. I normally use something like:

```
printf "$(python setup.py --version).r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
```

**Closed** 2020-08-02 04:20 UTC
